# Generated by Django 2.2.10 on 2021-03-01 04:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=10)),
                ('code_name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('summary', models.TextField(null=True)),
                ('chart_data_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('buy_price', models.FloatField(null=True)),
                ('buy_date', models.DateField(null=True)),
                ('buy_memo', models.TextField(null=True)),
                ('sell_price', models.FloatField(null=True)),
                ('sell_date', models.DateField(null=True)),
                ('sell_memo', models.TextField(null=True)),
                ('to_sell_price', models.FloatField(null=True)),
                ('to_sell_date', models.DateField(null=True)),
                ('to_buy_price', models.FloatField(null=True)),
                ('to_buy_date', models.DateField(null=True)),
            ],
        ),
    ]
